# Generated by Django 4.2.17 on 2025-01-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'LoginRegistration',
                'verbose_name_plural': 'LoginRegistration',
                'db_table': 'tbl_login_registration',
                'managed': True,
            },
        ),
    ]
